implementiere bessere Kommandozeile, implementiere cleanup

diff --git a/usr/sbin/linuxmuster-client b/usr/sbin/linuxmuster-client
--- a/usr/sbin/linuxmuster-client
+++ b/usr/sbin/linuxmuster-client
@@ -14,7 +14,7 @@
 # Netzwerkparameter linuxmuster.net
 ##v6 . /var/lib/linuxmuster/network.settings || exit 1
 ##v7 /var/lib/linuxmuster/setup.ini
-serverip=$(grep serverip /var/lib/linuxmuster/setup.ini | awk -F"=" '{print $2}' )
+##serverip=$(grep serverip /var/lib/linuxmuster/setup.ini | awk -F"=" '{gsub(/^[ \t]+/, "", $2); gsub(/[ \t]+$/, "", $2); print $2}' )
 
 # deklaration der globalen arrays
 declare -A TARGET_FILESET
@@ -29,126 +29,115 @@ check_startup
 function print_help() {
 cat <<End-of-help
 Anwendung:
-    $0 -a auto -c <Imagename> [-H <hardware-class>] [-p <password>]
-        Automatischer Modus, versucht das cloop aus dem Netz vollautomatisch zu installieren
-        <Imagename> muss einer der verfügbaren Cloops sein. Hardwareklasse und Passwort sind optional.
+    $0 list
+         Liste alle zur Verfügung stehenden Cloop-Pakete auf.
 
-    $0 -a get-cloop -c <Imagename> [-H <hardware-class>]
-        Holt ein cloop aus dem Netz und speichert die nötigen dateien in ${CONF_LINBODIR} ab.
-        Ist die Hardwareklasse nicht angegeben wird eine Datei start.conf.<Imagename> erstellt.
+    $0 -r <remotename> download
+         Lade folgendes Cloop-Paket herunter.
 
-    $0 -a configure -c <Imagename> [-H <hardware-class>] [-p <password>]
-        Bereitet ein heruntergeladenes cloop-Dateiset mit einem passenden postsync 
-        Skript zur Synchronisation auf Clients vor. Setzt das Passwort des Benutzers linuxadmin 
-	in der Hardwareklasse auf das mit -p angegebene Passwort, andernfalls auf den Wert in der 
-        Konfigurationsdatei.
-          
-Optionen:
-    -l                   Aktualisiert die Liste aller verfügbaren cloops und zeigt sie an.
-    -f                   überschreibe alle Dateien und fahre mit dem Download fort, autobackup start.conf
-    -c <Imagename>      welches cloop aus dem Netz verwendet wird
-    -H <hardware-class>  für welche Hardwareklasse das cloop heruntergeladen und konfiguriert wird
-    -p <password>        Ermöglicht es, das Passwort einer Hardwareklasse manuell zu setzen. 
+    $0 [-f] [-p <pw>] [-l <localname>] -r <remotename> <configure|auto>
+        Im Paket heißen start.conf.remotename, remotename.cloop und linuxmuster-client/remotename gleich
+        "auto" und "configure" konfiguriert genauso lokal, außer es wird "-l" angegeben, dann wird der überall verwendet.
 
-    Beispiel:
+	"auto" lädt auch noch vorher das Paket herunter, setzt danach das Passwort und räumt auf.
 
-     $0 -a auto -H myxenial -c xenial916
-    
-     Holt das Image "xenial916" vom linuxmuster-Server und legt anschließend eine HW-Klasse "myxenial" an, 
-     die das Image verwendet. Die Postsync-Einstellungen und Skripte werden im Verzeichnis
-        ${CONF_LINBODIR}/${CONF_POSTSYNCDIR}/myxenial/
-     angelegt. 
-     Das Passwort für linuxadmin wird bei der Synchronisation auf den in der Konfigurationsdatei 
-     vorgegebenen Wert gesetzt.
+    $0 [-p <pw>] -l <localname> setpw
+        Setze das Passwort in der Patchklasse linuxmuster-client/localname wie in der Konfigurationsdatei oder <pw> wenn angegeben.
+
+    $0 -l <localname> cleanup
+        Löscht ~-Dateien in der Patchklasse linuxmuster-client/localname
+
+#Optionen:
+#    -f                   überschreibe alle Dateien und fahre mit dem Download fort, autobackup start.conf
 
 End-of-help
 }
 
-PATCHCLASS_SET=0
-COMMONCLASS=""
+
+PATCHCLASS=""
+LOCALNAME=""
+REMOTENAME=""
+HOSTGROUP=""
+LAPASS=""
 FORCE=0
 
 # Optionen verarbeiten
-while getopts "la:c:fp:H:" opt; do
+#while getopts ":hla:c:fp:H:" opt; do
+while getopts "hfl:r:p:" opt; do
     case $opt in
-	l)
-	    ACTION=list-available
-	    ;;
-	a)
-            ACTION=$OPTARG
-            ;;
-	c)
-            CLOOP_NAME=$OPTARG
-            ;;
 	f)
 	    FORCE=1
 	    ;;
-	#    P)	
-	#	PATCHCLASS_SET=1
-	#        PATCHCLASS=$OPTARG
-	#        ;;
+	l)
+	    HOSTGROUP=$OPTARG
+	    PATCHCLASS=$OPTARG
+	    LOCALNAME=$OPTARG
+	    ;;
+	r)
+            REMOTENAME=$OPTARG
+            ;;
 	p)
 	    LAPASS=$OPTARG
 	    ;;
-	H)
-            HOSTGROUP=$OPTARG
-            ;;
-	\?)
+	\? | h)
             print_help
 	    exit 0
             ;;
     esac
 done
 
+shift $((OPTIND-1))
 
-case $ACTION in
-    auto)
-	if [ "x$CLOOP_NAME" == "x" ]; then
-            exit_error "Die Option -c <Imagename> muss angegeben werden. $0 -h für weitere Hilfe."
-	fi 
-	# Hardwareklasse wird CLOOP_NAME verwendet, außer es wurde gesetzt
-	HOSTGROUP=${HOSTGROUP:-$CLOOP_NAME}
-	get_available_images
-	is_image_available $CLOOP_NAME || { list_available_images; exit_error "Konnte kein Cloop mit dem angegebenen Namen ($CLOOP_NAME) finden."; }
-	
-	#PATCHCLASS_SET=1
-	#PATCHCLASS=$HOSTGROUP
-	# Cloop herunterladen
-	get_remote_cloop ${HOSTGROUP} ${CLOOP_NAME}
-	# Cloop konfigurieren
-	configure_cloop ${HOSTGROUP} ${CLOOP_NAME}
-	;;
-    get-cloop)
-	if [ "x$CLOOP_NAME" == "x" ]; then
-            exit_error "Die Option -c <Imagename> muss angegeben werden. $0 -h für weitere Hilfe."
-	fi 
-	# Hardwareklasse wird CLOOP_NAME verwendet, außer es wurde gesetzt
-	HOSTGROUP=${HOSTGROUP:-$CLOOP_NAME}
-	get_available_images
-	is_image_available $CLOOP_NAME || { list_available_images; exit_error "Konnte kein Cloop mit dem angegebenen Namen ($CLOOP_NAME) finden."; }
-	get_remote_cloop $HOSTGROUP $CLOOP_NAME
-	;;
-    configure)
-	if [ "x$CLOOP_NAME" == "x" ]; then
-            exit_error "Die Option -c <Imagename> muss angegeben werden. $0 -h für weitere Hilfe."
-	fi 
-	# Hardwareklasse wird CLOOP_NAME verwendet, außer es wurde gesetzt
-	HOSTGROUP=${HOSTGROUP:-$CLOOP_NAME}
-	configure_cloop ${HOSTGROUP} ${CLOOP_NAME}
-	;;
-    set-postsync-pass)
-	if [ "x$HOSTGROUP" == "x" ]; then
-            exit_error "Die Option -H <hardware-class> muss angegeben werden. $0 -h für weitere Hilfe."
-	fi 
-	#if [ $PATCHCLASS_SET -eq 0 ]; then 
-	#	PATCHCLASS=""
-	#fi
-	PATCHCLASS=$HOSTGROUP
-	set_password_to_postsync $PATCHCLASS
-	;;
-    list-available)
+case $@ in
+    list)
 	get_available_images
 	list_available_images
+	;;
+    download)
+	if [ "x$REMOTENAME" == "x" ]; then
+            exit_error "Die Option -r <remotename> muss angegeben werden. $0 list, um alle Möglichkeiten aufzulisten. $0 -h für weitere Hilfe."
+	fi 
+	# Hardwareklasse wird REMOTENAME verwendet, außer es wurde gesetzt
+	LOCALNAME=${LOCALNAME:-$REMOTENAME}
+	get_available_images
+	is_image_available $REMOTENAME || { list_available_images; exit_error "Konnte kein Cloop mit dem angegebenen Namen ($REMOTENAME) finden."; }
+	get_remote_cloop $LOCALNAME $REMOTENAME
+	;;
+    configure)
+	if [ "x$REMOTENAME" == "x" ]; then
+            exit_error "Die Option -r <remotename> muss angegeben werden. $0 list, um alle Möglichkeiten aufzulisten. $0 -h für weitere Hilfe."
+	fi 
+	# als LOCALNAME wird REMOTENAME verwendet, außer es wurde gesetzt
+	LOCALNAME=${LOCALNAME:-$REMOTENAME}
+	# simplifizierung: patchklasse, hwklasse und cloopname heißen gleich
+	configure_cloop ${LOCALNAME} ${LOCALNAME} ${LOCALNAME} ${REMOTENAME}
+	;;
+    auto)
+	if [ "x$REMOTENAME" == "x" ]; then
+            exit_error "Die Option -r <remotename> muss angegeben werden. $0 list, um alle Möglichkeiten aufzulisten. $0 -h für weitere Hilfe."
+	fi 
+	# als LOCALNAME wird REMOTENAME verwendet, außer es wurde gesetzt
+	LOCALNAME=${LOCALNAME:-$REMOTENAME}
+	get_available_images
+	is_image_available $REMOTENAME || { list_available_images; exit_error "Konnte kein Cloop mit dem angegebenen Namen ($REMOTENAME) finden."; }
+	# Cloop herunterladen
+	get_remote_cloop ${LOCALNAME} ${REMOTENAME}
+	# simplifizierung: patchklasse, hwklasse und cloopname heißen gleich
+	configure_cloop ${LOCALNAME} ${LOCALNAME} ${LOCALNAME} ${REMOTENAME}
+	# cleanup interactive
+	cleanup $LOCALNAME 1
+	;;
+    setpw)
+	if [ "x$LOCALNAME" == "x" ]; then
+            exit_error "Die Option -l <localname> muss angegeben werden. $0 -h für weitere Hilfe."
+	fi 
+	set_password_to_postsync $LOCALNAME
+	;;
+    cleanup)
+	if [ "x$LOCALNAME" == "x" ]; then
+            exit_error "Die Option -l <localname> muss angegeben werden. $0 -h für weitere Hilfe."
+	fi 
+	cleanup $LOCALNAME 0
 	;;
     *)
 	print_help
